<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>res\Icon\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="res\0984c1d48eb11ef.wav" />
    <None Remove="res\11986c2f439eb45.wav" />
    <None Remove="res\Back.jpeg" />
    <None Remove="res\FocusedRestart.png" />
    <None Remove="res\ForRestart.jpg" />
    <None Remove="res\icon.ico" />
    <None Remove="res\PressedRestart.png" />
    <None Remove="res\Restart.png" />
    <None Remove="res\Sprites.png" />
    <None Remove="res\with-applause.wav" />
    <None Remove="res\zvuk_-_muzhskoj_krik.wav" />
    <None Remove="zvuk-jelektroshoker.wav" />
    <None Remove="Без названия %282%29.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="res\Sounds\11986c2f439eb45.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="res\Images\Backgrounds\Back.jpeg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="res\Sounds\0984c1d48eb11ef.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="res\Images\ButtonSprites\FocusedRestart.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="res\Images\Backgrounds\ForRestart.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="res\Icon\icon.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="res\Images\ButtonSprites\PressedRestart.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="res\Images\ButtonSprites\Restart.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="res\Images\Backgrounds\screamer.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="res\Images\Sprites.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="res\Sounds\with-applause.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="res\Sounds\zvuk-jelektroshoker.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="res\Sounds\zvuk_-_muzhskoj_krik.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
