<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>res\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Back.jpeg" />
    <None Remove="ForRestart.jpg" />
    <None Remove="res\0984c1d48eb11ef.wav" />
    <None Remove="res\Back.jpeg" />
    <None Remove="res\FocusedRestart.png" />
    <None Remove="res\ForRestart.jpg" />
    <None Remove="res\icon.ico" />
    <None Remove="res\PressedRestart.png" />
    <None Remove="res\Restart.png" />
    <None Remove="res\Sprites.png" />
    <None Remove="res\with-applause.wav" />
    <None Remove="res\zvuk_-_muzhskoj_krik.wav" />
    <None Remove="screamer.jpg" />
    <None Remove="zvuk-jelektroshoker.wav" />
    <None Remove="Без названия %282%29.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="res\Back.jpeg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="res\0984c1d48eb11ef.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="res\FocusedRestart.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="res\ForRestart.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="res\icon.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="res\PressedRestart.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="res\Restart.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="res\screamer.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="res\Sprites.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="res\with-applause.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="res\zvuk-jelektroshoker.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="res\zvuk_-_muzhskoj_krik.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Resource Include="Back.jpeg" />
    <Resource Include="ForRestart.jpg" />
    <Resource Include="res\Без названия %282%29.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="screamer.jpg" />
  </ItemGroup>

</Project>
